const CURRICULUM = {
    'English': {
        'A1': [
            // Module 1: Foundations (15 lessons)
            { module: 'Module 1: Foundations', id: 'eng-a1-1', title: 'Unit 1: The Alphabet', topic: 'English alphabet, Phonics basics' },
            { module: 'Module 1: Foundations', id: 'eng-a1-2', title: 'Unit 2: Vowel Sounds', topic: 'A, E, I, O, U pronunciation' },
            { module: 'Module 1: Foundations', id: 'eng-a1-3', title: 'Unit 3: Consonant Sounds', topic: 'B, C, D, F, G pronunciation' },
            { module: 'Module 1: Foundations', id: 'eng-a1-4', title: 'Unit 4: Greetings', topic: 'Hello, Hi, Good morning/afternoon/evening' },
            { module: 'Module 1: Foundations', id: 'eng-a1-5', title: 'Unit 5: Farewells', topic: 'Goodbye, See you, Take care' },
            { module: 'Module 1: Foundations', id: 'eng-a1-6', title: 'Unit 6: Introductions', topic: 'My name is..., Nice to meet you' },
            { module: 'Module 1: Foundations', id: 'eng-a1-7', title: 'Unit 7: Verb To Be (I/You)', topic: 'I am, You are' },
            { module: 'Module 1: Foundations', id: 'eng-a1-8', title: 'Unit 8: Verb To Be (He/She/It)', topic: 'He is, She is, It is' },
            { module: 'Module 1: Foundations', id: 'eng-a1-9', title: 'Unit 9: Verb To Be (We/They)', topic: 'We are, They are' },
            { module: 'Module 1: Foundations', id: 'eng-a1-10', title: 'Unit 10: Subject Pronouns', topic: 'I, You, He, She, It, We, They' },
            { module: 'Module 1: Foundations', id: 'eng-a1-11', title: 'Unit 11: Articles', topic: 'A, An, The' },
            { module: 'Module 1: Foundations', id: 'eng-a1-12', title: 'Unit 12: This/That', topic: 'Demonstrative pronouns singular' },
            { module: 'Module 1: Foundations', id: 'eng-a1-13', title: 'Unit 13: These/Those', topic: 'Demonstrative pronouns plural' },
            { module: 'Module 1: Foundations', id: 'eng-a1-14', title: 'Unit 14: Question Words', topic: 'What, Where, When, Who, How' },
            { module: 'Module 1: Foundations', id: 'eng-a1-15', title: 'Unit 15: Yes/No Questions', topic: 'Is it? Are you? Do you?' },
            // Module 2: Numbers & Colors (12 lessons)
            { module: 'Module 2: Numbers & Colors', id: 'eng-a1-16', title: 'Unit 16: Numbers 1-10', topic: 'One through ten' },
            { module: 'Module 2: Numbers & Colors', id: 'eng-a1-17', title: 'Unit 17: Numbers 11-20', topic: 'Eleven through twenty' },
            { module: 'Module 2: Numbers & Colors', id: 'eng-a1-18', title: 'Unit 18: Numbers 21-50', topic: 'Twenty-one through fifty' },
            { module: 'Module 2: Numbers & Colors', id: 'eng-a1-19', title: 'Unit 19: Numbers 51-100', topic: 'Fifty-one through one hundred' },
            { module: 'Module 2: Numbers & Colors', id: 'eng-a1-20', title: 'Unit 20: Large Numbers', topic: 'Hundreds, thousands, millions' },
            { module: 'Module 2: Numbers & Colors', id: 'eng-a1-21', title: 'Unit 21: Ordinal Numbers', topic: 'First, Second, Third...' },
            { module: 'Module 2: Numbers & Colors', id: 'eng-a1-22', title: 'Unit 22: Basic Colors', topic: 'Red, Blue, Green, Yellow' },
            { module: 'Module 2: Numbers & Colors', id: 'eng-a1-23', title: 'Unit 23: More Colors', topic: 'Orange, Purple, Pink, Brown, Black, White' },
            { module: 'Module 2: Numbers & Colors', id: 'eng-a1-24', title: 'Unit 24: Describing Objects', topic: 'It is + color, It is + size' },
            { module: 'Module 2: Numbers & Colors', id: 'eng-a1-25', title: 'Unit 25: Shapes', topic: 'Circle, Square, Triangle, Rectangle' },
            { module: 'Module 2: Numbers & Colors', id: 'eng-a1-26', title: 'Unit 26: Sizes', topic: 'Big, Small, Medium, Large' },
            { module: 'Module 2: Numbers & Colors', id: 'eng-a1-27', title: 'Unit 27: Review Numbers & Colors', topic: 'Practice and consolidation' },
            // Module 3: Family & People (12 lessons)
            { module: 'Module 3: Family & People', id: 'eng-a1-28', title: 'Unit 28: Immediate Family', topic: 'Mother, Father, Sister, Brother' },
            { module: 'Module 3: Family & People', id: 'eng-a1-29', title: 'Unit 29: Extended Family', topic: 'Grandfather, Grandmother, Aunt, Uncle' },
            { module: 'Module 3: Family & People', id: 'eng-a1-30', title: 'Unit 30: Family Relations', topic: 'Cousin, Nephew, Niece' },
            { module: 'Module 3: Family & People', id: 'eng-a1-31', title: 'Unit 31: Possessive Adjectives', topic: 'My, Your, His, Her, Our, Their' },
            { module: 'Module 3: Family & People', id: 'eng-a1-32', title: 'Unit 32: Possessive Pronouns', topic: 'Mine, Yours, His, Hers, Ours, Theirs' },
            { module: 'Module 3: Family & People', id: 'eng-a1-33', title: 'Unit 33: Describing Appearance', topic: 'Tall, Short, Young, Old' },
            { module: 'Module 3: Family & People', id: 'eng-a1-34', title: 'Unit 34: Describing Character', topic: 'Nice, Kind, Funny, Smart' },
            { module: 'Module 3: Family & People', id: 'eng-a1-35', title: 'Unit 35: Physical Features', topic: 'Hair color, Eye color' },
            { module: 'Module 3: Family & People', id: 'eng-a1-36', title: 'Unit 36: Age', topic: 'How old are you? I am ... years old' },
            { module: 'Module 3: Family & People', id: 'eng-a1-37', title: 'Unit 37: Nationalities', topic: 'American, British, French, Spanish' },
            { module: 'Module 3: Family & People', id: 'eng-a1-38', title: 'Unit 38: Countries', topic: 'USA, UK, France, Spain, Japan' },
            { module: 'Module 3: Family & People', id: 'eng-a1-39', title: 'Unit 39: Jobs (Basic)', topic: 'Teacher, Doctor, Student, Engineer' },
            // Module 4: Daily Life (15 lessons)
            { module: 'Module 4: Daily Life', id: 'eng-a1-40', title: 'Unit 40: Morning Routine', topic: 'Wake up, Get up, Take a shower' },
            { module: 'Module 4: Daily Life', id: 'eng-a1-41', title: 'Unit 41: Day Routine', topic: 'Go to work/school, Have lunch' },
            { module: 'Module 4: Daily Life', id: 'eng-a1-42', title: 'Unit 42: Evening Routine', topic: 'Come home, Have dinner, Go to bed' },
            { module: 'Module 4: Daily Life', id: 'eng-a1-43', title: 'Unit 43: Present Simple (Affirmative)', topic: 'I work, You study, We play' },
            { module: 'Module 4: Daily Life', id: 'eng-a1-44', title: 'Unit 44: Present Simple (Third Person)', topic: 'She works, He studies' },
            { module: 'Module 4: Daily Life', id: 'eng-a1-45', title: 'Unit 45: Present Simple (Negative)', topic: 'I do not work, She does not study' },
            { module: 'Module 4: Daily Life', id: 'eng-a1-46', title: 'Unit 46: Present Simple (Questions)', topic: 'Do you work? Does she study?' },
            { module: 'Module 4: Daily Life', id: 'eng-a1-47', title: 'Unit 47: Telling Time (Hours)', topic: 'It is one oclock, two oclock' },
            { module: 'Module 4: Daily Life', id: 'eng-a1-48', title: 'Unit 48: Telling Time (Minutes)', topic: 'Half past, Quarter past/to' },
            { module: 'Module 4: Daily Life', id: 'eng-a1-49', title: 'Unit 49: Days of the Week', topic: 'Monday through Sunday' },
            { module: 'Module 4: Daily Life', id: 'eng-a1-50', title: 'Unit 50: Months of the Year', topic: 'January through December' },
            { module: 'Module 4: Daily Life', id: 'eng-a1-51', title: 'Unit 51: Seasons', topic: 'Spring, Summer, Autumn, Winter' },
            { module: 'Module 4: Daily Life', id: 'eng-a1-52', title: 'Unit 52: Frequency Adverbs', topic: 'Always, Usually, Sometimes, Never' },
            { module: 'Module 4: Daily Life', id: 'eng-a1-53', title: 'Unit 53: Weekend Activities', topic: 'Hobbies and leisure' },
            { module: 'Module 4: Daily Life', id: 'eng-a1-54', title: 'Unit 54: Review Daily Life', topic: 'Practice routines and time' },
            // Module 5: Food & Drink (12 lessons)
            { module: 'Module 5: Food & Drink', id: 'eng-a1-55', title: 'Unit 55: Fruits', topic: 'Apple, Orange, Banana, Grape' },
            { module: 'Module 5: Food & Drink', id: 'eng-a1-56', title: 'Unit 56: Vegetables', topic: 'Carrot, Tomato, Potato, Onion' },
            { module: 'Module 5: Food & Drink', id: 'eng-a1-57', title: 'Unit 57: Meat & Fish', topic: 'Chicken, Beef, Pork, Fish' },
            { module: 'Module 5: Food & Drink', id: 'eng-a1-58', title: 'Unit 58: Dairy & Bread', topic: 'Milk, Cheese, Bread, Eggs' },
            { module: 'Module 5: Food & Drink', id: 'eng-a1-59', title: 'Unit 59: Drinks', topic: 'Water, Coffee, Tea, Juice' },
            { module: 'Module 5: Food & Drink', id: 'eng-a1-60', title: 'Unit 60: Meals', topic: 'Breakfast, Lunch, Dinner' },
            { module: 'Module 5: Food & Drink', id: 'eng-a1-61', title: 'Unit 61: Likes & Dislikes', topic: 'I like..., I do not like...' },
            { module: 'Module 5: Food & Drink', id: 'eng-a1-62', title: 'Unit 62: At a Restaurant', topic: 'Can I have...?, The bill please' },
            { module: 'Module 5: Food & Drink', id: 'eng-a1-63', title: 'Unit 63: Ordering Food', topic: 'I would like..., For me...' },
            { module: 'Module 5: Food & Drink', id: 'eng-a1-64', title: 'Unit 64: Countable/Uncountable', topic: 'Some, Any, Much, Many' },
            { module: 'Module 5: Food & Drink', id: 'eng-a1-65', title: 'Unit 65: Quantities', topic: 'A piece of, A glass of, A bottle of' },
            { module: 'Module 5: Food & Drink', id: 'eng-a1-66', title: 'Unit 66: Food Review', topic: 'Practice and conversation' },
            // Module 6: Places & Weather (10 lessons)
            { module: 'Module 6: Places & Weather', id: 'eng-a1-67', title: 'Unit 67: Places in Town', topic: 'Bank, Hospital, School, Park' },
            { module: 'Module 6: Places & Weather', id: 'eng-a1-68', title: 'Unit 68: Shops', topic: 'Supermarket, Bakery, Pharmacy' },
            { module: 'Module 6: Places & Weather', id: 'eng-a1-69', title: 'Unit 69: There is/There are', topic: 'Describing locations' },
            { module: 'Module 6: Places & Weather', id: 'eng-a1-70', title: 'Unit 70: Weather Vocabulary', topic: 'Sunny, Rainy, Cloudy, Windy' },
            { module: 'Module 6: Places & Weather', id: 'eng-a1-71', title: 'Unit 71: Weather Expressions', topic: 'It is hot, cold, raining, snowing' },
            { module: 'Module 6: Places & Weather', id: 'eng-a1-72', title: 'Unit 72: Prepositions of Place', topic: 'In, On, At, Next to, Behind' },
            { module: 'Module 6: Places & Weather', id: 'eng-a1-73', title: 'Unit 73: Giving Directions', topic: 'Go straight, Turn left/right' },
            { module: 'Module 6: Places & Weather', id: 'eng-a1-74', title: 'Unit 74: Asking for Directions', topic: 'Where is...? How do I get to...?' },
            { module: 'Module 6: Places & Weather', id: 'eng-a1-75', title: 'Unit 75: At Home', topic: 'Rooms and furniture' },
            { module: 'Module 6: Places & Weather', id: 'eng-a1-76', title: 'Unit 76: Places Review', topic: 'Practice and consolidation' },
            // Module 7: Transport & Clothes (10 lessons)
            { module: 'Module 7: Transport & Clothes', id: 'eng-a1-77', title: 'Unit 77: Transport Types', topic: 'Bus, Train, Car, Plane, Bike' },
            { module: 'Module 7: Transport & Clothes', id: 'eng-a1-78', title: 'Unit 78: Using Transport', topic: 'Take the bus, Drive a car' },
            { module: 'Module 7: Transport & Clothes', id: 'eng-a1-79', title: 'Unit 79: Buying Tickets', topic: 'One way, Return, Platform' },
            { module: 'Module 7: Transport & Clothes', id: 'eng-a1-80', title: 'Unit 80: Clothes Upper Body', topic: 'Shirt, T-shirt, Jacket, Sweater' },
            { module: 'Module 7: Transport & Clothes', id: 'eng-a1-81', title: 'Unit 81: Clothes Lower Body', topic: 'Pants, Jeans, Skirt, Shorts' },
            { module: 'Module 7: Transport & Clothes', id: 'eng-a1-82', title: 'Unit 82: Footwear & Accessories', topic: 'Shoes, Boots, Hat, Bag' },
            { module: 'Module 7: Transport & Clothes', id: 'eng-a1-83', title: 'Unit 83: Present Continuous Form', topic: 'I am eating, She is working' },
            { module: 'Module 7: Transport & Clothes', id: 'eng-a1-84', title: 'Unit 84: Present Continuous Use', topic: 'Actions happening now' },
            { module: 'Module 7: Transport & Clothes', id: 'eng-a1-85', title: 'Unit 85: Present Simple vs Continuous', topic: 'Habits vs current actions' },
            { module: 'Module 7: Transport & Clothes', id: 'eng-a1-86', title: 'Unit 86: A1 Final Review', topic: 'Complete A1 review' },
            { module: 'Assessment', id: 'eng-a1-exam', type: 'exam', title: 'A1 Final Exam', topic: 'Beginner Proficiency Assessment', requiredScore: 80 }
        ],
        'A2': [
            // Module 1: Home & Past (15 lessons)
            { module: 'Module 1: Home & Past', id: 'eng-a2-1', title: 'Unit 1: Rooms of the House', topic: 'Kitchen, Bedroom, Bathroom, Living room' },
            { module: 'Module 1: Home & Past', id: 'eng-a2-2', title: 'Unit 2: Furniture', topic: 'Sofa, Table, Bed, Chair, Desk' },
            { module: 'Module 1: Home & Past', id: 'eng-a2-3', title: 'Unit 3: Household Items', topic: 'Lamp, Mirror, Carpet, Curtains' },
            { module: 'Module 1: Home & Past', id: 'eng-a2-4', title: 'Unit 4: Kitchen Items', topic: 'Fridge, Oven, Microwave, Sink' },
            { module: 'Module 1: Home & Past', id: 'eng-a2-5', title: 'Unit 5: Past Simple Regular', topic: 'Worked, Played, Studied, Watched' },
            { module: 'Module 1: Home & Past', id: 'eng-a2-6', title: 'Unit 6: Past Simple Irregular 1', topic: 'Went, Had, Saw, Did, Made' },
            { module: 'Module 1: Home & Past', id: 'eng-a2-7', title: 'Unit 7: Past Simple Irregular 2', topic: 'Ate, Drank, Bought, Took, Gave' },
            { module: 'Module 1: Home & Past', id: 'eng-a2-8', title: 'Unit 8: Past Simple Negative', topic: 'Did not go, Did not see' },
            { module: 'Module 1: Home & Past', id: 'eng-a2-9', title: 'Unit 9: Past Simple Questions', topic: 'Did you go? Where did you go?' },
            { module: 'Module 1: Home & Past', id: 'eng-a2-10', title: 'Unit 10: Childhood Memories', topic: 'When I was young...' },
            { module: 'Module 1: Home & Past', id: 'eng-a2-11', title: 'Unit 11: Used to', topic: 'I used to play... He used to live...' },
            { module: 'Module 1: Home & Past', id: 'eng-a2-12', title: 'Unit 12: Past Time Expressions', topic: 'Yesterday, Last week, Ago' },
            { module: 'Module 1: Home & Past', id: 'eng-a2-13', title: 'Unit 13: Telling Stories', topic: 'First, Then, After that, Finally' },
            { module: 'Module 1: Home & Past', id: 'eng-a2-14', title: 'Unit 14: Biography', topic: 'Was born, Grew up, Moved to' },
            { module: 'Module 1: Home & Past', id: 'eng-a2-15', title: 'Unit 15: Home Review', topic: 'Practice describing homes' },
            // Module 2: Practical Skills (15 lessons)
            { module: 'Module 2: Practical Skills', id: 'eng-a2-16', title: 'Unit 16: Giving Directions', topic: 'Turn left, Go straight, Cross the street' },
            { module: 'Module 2: Practical Skills', id: 'eng-a2-17', title: 'Unit 17: Asking for Help', topic: 'Excuse me, Can you help me?' },
            { module: 'Module 2: Practical Skills', id: 'eng-a2-18', title: 'Unit 18: Shopping Vocabulary', topic: 'Price, Size, Receipt, Change' },
            { module: 'Module 2: Practical Skills', id: 'eng-a2-19', title: 'Unit 19: Shopping Conversations', topic: 'How much? Too expensive' },
            { module: 'Module 2: Practical Skills', id: 'eng-a2-20', title: 'Unit 20: At the Doctor', topic: 'Body parts, I have a headache' },
            { module: 'Module 2: Practical Skills', id: 'eng-a2-21', title: 'Unit 21: Health Problems', topic: 'Cold, Flu, Fever, Pain' },
            { module: 'Module 2: Practical Skills', id: 'eng-a2-22', title: 'Unit 22: At the Pharmacy', topic: 'Medicine, Prescription, Pills' },
            { module: 'Module 2: Practical Skills', id: 'eng-a2-23', title: 'Unit 23: Should/Should not', topic: 'Giving advice' },
            { module: 'Module 2: Practical Skills', id: 'eng-a2-24', title: 'Unit 24: Making Appointments', topic: 'I would like to book...' },
            { module: 'Module 2: Practical Skills', id: 'eng-a2-25', title: 'Unit 25: Phone Conversations', topic: 'Hello, May I speak to...?' },
            { module: 'Module 2: Practical Skills', id: 'eng-a2-26', title: 'Unit 26: Emails Basic', topic: 'Subject, Dear, Best regards' },
            { module: 'Module 2: Practical Skills', id: 'eng-a2-27', title: 'Unit 27: Imperatives', topic: 'Wait! Stop! Come here!' },
            { module: 'Module 2: Practical Skills', id: 'eng-a2-28', title: 'Unit 28: Object Pronouns', topic: 'Me, You, Him, Her, It, Us, Them' },
            { module: 'Module 2: Practical Skills', id: 'eng-a2-29', title: 'Unit 29: Reflexive Pronouns', topic: 'Myself, Yourself, Himself' },
            { module: 'Module 2: Practical Skills', id: 'eng-a2-30', title: 'Unit 30: Practical Review', topic: 'Real-life situations practice' },
            // Module 3: Future & Plans (15 lessons)
            { module: 'Module 3: Future & Plans', id: 'eng-a2-31', title: 'Unit 31: Going to (Plans)', topic: 'I am going to study...' },
            { module: 'Module 3: Future & Plans', id: 'eng-a2-32', title: 'Unit 32: Going to (Predictions)', topic: 'It is going to rain' },
            { module: 'Module 3: Future & Plans', id: 'eng-a2-33', title: 'Unit 33: Will (Decisions)', topic: 'I will help you' },
            { module: 'Module 3: Future & Plans', id: 'eng-a2-34', title: 'Unit 34: Will (Predictions)', topic: 'It will be sunny tomorrow' },
            { module: 'Module 3: Future & Plans', id: 'eng-a2-35', title: 'Unit 35: Will vs Going to', topic: 'Choosing the right future' },
            { module: 'Module 3: Future & Plans', id: 'eng-a2-36', title: 'Unit 36: Travel Vocabulary', topic: 'Airport, Hotel, Passport, Visa' },
            { module: 'Module 3: Future & Plans', id: 'eng-a2-37', title: 'Unit 37: At the Airport', topic: 'Check-in, Gate, Boarding' },
            { module: 'Module 3: Future & Plans', id: 'eng-a2-38', title: 'Unit 38: At the Hotel', topic: 'Reservation, Room, Key' },
            { module: 'Module 3: Future & Plans', id: 'eng-a2-39', title: 'Unit 39: Making Reservations', topic: 'I would like to book...' },
            { module: 'Module 3: Future & Plans', id: 'eng-a2-40', title: 'Unit 40: Tourist Activities', topic: 'Sightseeing, Museums, Tours' },
            { module: 'Module 3: Future & Plans', id: 'eng-a2-41', title: 'Unit 41: Invitations', topic: 'Would you like to...?' },
            { module: 'Module 3: Future & Plans', id: 'eng-a2-42', title: 'Unit 42: Accepting/Declining', topic: 'Yes, I would love to / Sorry, I can not' },
            { module: 'Module 3: Future & Plans', id: 'eng-a2-43', title: 'Unit 43: Comparatives', topic: 'Bigger, More expensive, Better' },
            { module: 'Module 3: Future & Plans', id: 'eng-a2-44', title: 'Unit 44: Superlatives', topic: 'The biggest, The most, The best' },
            { module: 'Module 3: Future & Plans', id: 'eng-a2-45', title: 'Unit 45: Future Review', topic: 'Practice plans and predictions' },
            // Module 4: Hobbies & Free Time (10 lessons)
            { module: 'Module 4: Hobbies', id: 'eng-a2-46', title: 'Unit 46: Sports', topic: 'Football, Tennis, Swimming, Running' },
            { module: 'Module 4: Hobbies', id: 'eng-a2-47', title: 'Unit 47: Music', topic: 'Instruments, Genres, Concerts' },
            { module: 'Module 4: Hobbies', id: 'eng-a2-48', title: 'Unit 48: Movies & TV', topic: 'Genres, Actors, Series' },
            { module: 'Module 4: Hobbies', id: 'eng-a2-49', title: 'Unit 49: Reading', topic: 'Books, Magazines, Authors' },
            { module: 'Module 4: Hobbies', id: 'eng-a2-50', title: 'Unit 50: Gerunds (-ing forms)', topic: 'I like swimming, I enjoy reading' },
            { module: 'Module 4: Hobbies', id: 'eng-a2-51', title: 'Unit 51: Infinitives (to + verb)', topic: 'I want to go, I need to study' },
            { module: 'Module 4: Hobbies', id: 'eng-a2-52', title: 'Unit 52: Hobbies Conversation', topic: 'What do you like doing?' },
            { module: 'Module 4: Hobbies', id: 'eng-a2-53', title: 'Unit 53: Past Continuous', topic: 'I was walking when...' },
            { module: 'Module 4: Hobbies', id: 'eng-a2-54', title: 'Unit 54: Past Simple vs Continuous', topic: 'While I was... someone...' },
            { module: 'Module 4: Hobbies', id: 'eng-a2-55', title: 'Unit 55: A2 Final Review', topic: 'Complete A2 review' },
            { module: 'Assessment', id: 'eng-a2-exam', type: 'exam', title: 'A2 Final Exam', topic: 'Elementary Proficiency Assessment', requiredScore: 80 }
        ],
        'B1': [
            // Module 1: Experiences (12 lessons)
            { module: 'Module 1: Experiences', id: 'eng-b1-1', title: 'Unit 1: Present Perfect Form', topic: 'I have visited, She has seen' },
            { module: 'Module 1: Experiences', id: 'eng-b1-2', title: 'Unit 2: Present Perfect vs Past Simple', topic: 'Have you ever...? vs Did you...?' },
            { module: 'Module 1: Experiences', id: 'eng-b1-3', title: 'Unit 3: Ever/Never', topic: 'Have you ever been to...?' },
            { module: 'Module 1: Experiences', id: 'eng-b1-4', title: 'Unit 4: Already/Yet/Just', topic: 'I have already done it' },
            { module: 'Module 1: Experiences', id: 'eng-b1-5', title: 'Unit 5: For/Since', topic: 'For three years, Since 2020' },
            { module: 'Module 1: Experiences', id: 'eng-b1-6', title: 'Unit 6: How long...?', topic: 'Duration questions' },
            { module: 'Module 1: Experiences', id: 'eng-b1-7', title: 'Unit 7: Present Perfect Continuous', topic: 'I have been working' },
            { module: 'Module 1: Experiences', id: 'eng-b1-8', title: 'Unit 8: Past Continuous Review', topic: 'I was doing when...' },
            { module: 'Module 1: Experiences', id: 'eng-b1-9', title: 'Unit 9: Past Perfect', topic: 'I had finished before...' },
            { module: 'Module 1: Experiences', id: 'eng-b1-10', title: 'Unit 10: Narrative Tenses', topic: 'Telling stories in the past' },
            { module: 'Module 1: Experiences', id: 'eng-b1-11', title: 'Unit 11: Storytelling', topic: 'Sequencing events' },
            { module: 'Module 1: Experiences', id: 'eng-b1-12', title: 'Unit 12: Life Experiences', topic: 'Talking about achievements' },
            // Module 2: Work & Education (12 lessons)
            { module: 'Module 2: Work & Education', id: 'eng-b1-13', title: 'Unit 13: Job Vocabulary', topic: 'Careers, Skills, Duties' },
            { module: 'Module 2: Work & Education', id: 'eng-b1-14', title: 'Unit 14: Job Descriptions', topic: 'Responsibilities, Qualifications' },
            { module: 'Module 2: Work & Education', id: 'eng-b1-15', title: 'Unit 15: Job Interview', topic: 'Common questions and answers' },
            { module: 'Module 2: Work & Education', id: 'eng-b1-16', title: 'Unit 16: CV Writing', topic: 'Resume format and content' },
            { module: 'Module 2: Work & Education', id: 'eng-b1-17', title: 'Unit 17: Cover Letters', topic: 'Professional letter writing' },
            { module: 'Module 2: Work & Education', id: 'eng-b1-18', title: 'Unit 18: Education System', topic: 'School, University, Degrees' },
            { module: 'Module 2: Work & Education', id: 'eng-b1-19', title: 'Unit 19: Academic Vocabulary', topic: 'Exam, Course, Grade, Lecture' },
            { module: 'Module 2: Work & Education', id: 'eng-b1-20', title: 'Unit 20: Passive Voice Present', topic: 'Is made, Are produced' },
            { module: 'Module 2: Work & Education', id: 'eng-b1-21', title: 'Unit 21: Passive Voice Past', topic: 'Was written, Were built' },
            { module: 'Module 2: Work & Education', id: 'eng-b1-22', title: 'Unit 22: Relative Clauses (who/which)', topic: 'The person who..., The thing which...' },
            { module: 'Module 2: Work & Education', id: 'eng-b1-23', title: 'Unit 23: Relative Clauses (that/where)', topic: 'The place where..., The day that...' },
            { module: 'Module 2: Work & Education', id: 'eng-b1-24', title: 'Unit 24: Work Review', topic: 'Professional communication' },
            // Module 3: Opinions & Conditions (12 lessons)
            { module: 'Module 3: Opinions', id: 'eng-b1-25', title: 'Unit 25: Expressing Opinions', topic: 'I think..., In my opinion...' },
            { module: 'Module 3: Opinions', id: 'eng-b1-26', title: 'Unit 26: Agreeing/Disagreeing', topic: 'You are right, I disagree' },
            { module: 'Module 3: Opinions', id: 'eng-b1-27', title: 'Unit 27: Giving Reasons', topic: 'Because, Since, As' },
            { module: 'Module 3: Opinions', id: 'eng-b1-28', title: 'Unit 28: First Conditional', topic: 'If + present, will + verb' },
            { module: 'Module 3: Opinions', id: 'eng-b1-29', title: 'Unit 29: Second Conditional', topic: 'If + past, would + verb' },
            { module: 'Module 3: Opinions', id: 'eng-b1-30', title: 'Unit 30: First vs Second Conditional', topic: 'Real vs Unreal conditions' },
            { module: 'Module 3: Opinions', id: 'eng-b1-31', title: 'Unit 31: Unless', topic: 'Unless = If not' },
            { module: 'Module 3: Opinions', id: 'eng-b1-32', title: 'Unit 32: Modal Verbs Review', topic: 'Can, Could, May, Might' },
            { module: 'Module 3: Opinions', id: 'eng-b1-33', title: 'Unit 33: Must/Have to', topic: 'Obligation and necessity' },
            { module: 'Module 3: Opinions', id: 'eng-b1-34', title: 'Unit 34: Should/Ought to', topic: 'Advice and recommendations' },
            { module: 'Module 3: Opinions', id: 'eng-b1-35', title: 'Unit 35: Might/Could (Possibility)', topic: 'It might rain, He could be sick' },
            { module: 'Module 3: Opinions', id: 'eng-b1-36', title: 'Unit 36: Opinions Review', topic: 'Debating and discussing' },
            // Module 4: Communication (8 lessons)
            { module: 'Module 4: Communication', id: 'eng-b1-37', title: 'Unit 37: Reported Speech (Present)', topic: 'He says that...' },
            { module: 'Module 4: Communication', id: 'eng-b1-38', title: 'Unit 38: Reported Speech (Past)', topic: 'He said that...' },
            { module: 'Module 4: Communication', id: 'eng-b1-39', title: 'Unit 39: Reported Questions', topic: 'He asked if/what...' },
            { module: 'Module 4: Communication', id: 'eng-b1-40', title: 'Unit 40: Phrasal Verbs Common', topic: 'Get up, Look after, Turn on' },
            { module: 'Module 4: Communication', id: 'eng-b1-41', title: 'Unit 41: Phrasal Verbs Work', topic: 'Take over, Set up, Carry out' },
            { module: 'Module 4: Communication', id: 'eng-b1-42', title: 'Unit 42: Connectors', topic: 'However, Therefore, Although' },
            { module: 'Module 4: Communication', id: 'eng-b1-43', title: 'Unit 43: Writing Essays', topic: 'Introduction, Body, Conclusion' },
            { module: 'Module 4: Communication', id: 'eng-b1-44', title: 'Unit 44: B1 Final Review', topic: 'Complete B1 review' },
            { module: 'Assessment', id: 'eng-b1-exam', type: 'exam', title: 'B1 Final Exam', topic: 'Intermediate Proficiency Assessment', requiredScore: 80 }
        ],
        'B2': [
            // Module 1: Advanced Communication (15 lessons)
            { module: 'Module 1: Advanced Communication', id: 'eng-b2-1', title: 'Unit 1: Media & News', topic: 'Newspaper, Television, Internet news' },
            { module: 'Module 1: Advanced Communication', id: 'eng-b2-2', title: 'Unit 2: Fake News', topic: 'Critical thinking, Sources, Bias' },
            { module: 'Module 1: Advanced Communication', id: 'eng-b2-3', title: 'Unit 3: Social Media', topic: 'Platforms, Influence, Privacy' },
            { module: 'Module 1: Advanced Communication', id: 'eng-b2-4', title: 'Unit 4: Environment Issues', topic: 'Climate change, Pollution' },
            { module: 'Module 1: Advanced Communication', id: 'eng-b2-5', title: 'Unit 5: Sustainability', topic: 'Recycling, Renewable energy' },
            { module: 'Module 1: Advanced Communication', id: 'eng-b2-6', title: 'Unit 6: Global Problems', topic: 'Poverty, Inequality, Health' },
            { module: 'Module 1: Advanced Communication', id: 'eng-b2-7', title: 'Unit 7: Reported Speech Advanced', topic: 'He said that he had...' },
            { module: 'Module 1: Advanced Communication', id: 'eng-b2-8', title: 'Unit 8: Reporting Verbs', topic: 'Claim, Suggest, Deny, Admit' },
            { module: 'Module 1: Advanced Communication', id: 'eng-b2-9', title: 'Unit 9: Advanced Passive', topic: 'It is believed that..., He is said to...' },
            { module: 'Module 1: Advanced Communication', id: 'eng-b2-10', title: 'Unit 10: Have/Get Something Done', topic: 'I had my car repaired' },
            { module: 'Module 1: Advanced Communication', id: 'eng-b2-11', title: 'Unit 11: Third Conditional', topic: 'If I had known, I would have...' },
            { module: 'Module 1: Advanced Communication', id: 'eng-b2-12', title: 'Unit 12: Mixed Conditionals', topic: 'If I had studied, I would be...' },
            { module: 'Module 1: Advanced Communication', id: 'eng-b2-13', title: 'Unit 13: Wish/If only (Present)', topic: 'I wish I knew...' },
            { module: 'Module 1: Advanced Communication', id: 'eng-b2-14', title: 'Unit 14: Wish/If only (Past)', topic: 'I wish I had known...' },
            { module: 'Module 1: Advanced Communication', id: 'eng-b2-15', title: 'Unit 15: Communication Review', topic: 'Complex structures practice' },
            // Module 2: Technology & Society (12 lessons)
            { module: 'Module 2: Technology', id: 'eng-b2-16', title: 'Unit 16: Technology Vocabulary', topic: 'AI, Apps, Cloud, Data' },
            { module: 'Module 2: Technology', id: 'eng-b2-17', title: 'Unit 17: Future of Technology', topic: 'Predictions and possibilities' },
            { module: 'Module 2: Technology', id: 'eng-b2-18', title: 'Unit 18: Work and Technology', topic: 'Remote work, Automation' },
            { module: 'Module 2: Technology', id: 'eng-b2-19', title: 'Unit 19: Modals of Deduction', topic: 'Must be, Could be, Can not be' },
            { module: 'Module 2: Technology', id: 'eng-b2-20', title: 'Unit 20: Modals in the Past', topic: 'Must have, Could have, Should have' },
            { module: 'Module 2: Technology', id: 'eng-b2-21', title: 'Unit 21: Culture & Customs', topic: 'Traditions, Stereotypes, Values' },
            { module: 'Module 2: Technology', id: 'eng-b2-22', title: 'Unit 22: Idiomatic Expressions', topic: 'Common idioms and meanings' },
            { module: 'Module 2: Technology', id: 'eng-b2-23', title: 'Unit 23: Phrasal Verbs Advanced', topic: 'Come across, Put up with' },
            { module: 'Module 2: Technology', id: 'eng-b2-24', title: 'Unit 24: Collocations', topic: 'Make a decision, Take responsibility' },
            { module: 'Module 2: Technology', id: 'eng-b2-25', title: 'Unit 25: Formal Writing', topic: 'Essays, Reports, Reviews' },
            { module: 'Module 2: Technology', id: 'eng-b2-26', title: 'Unit 26: Academic Writing', topic: 'Citations, Arguments, Structure' },
            { module: 'Module 2: Technology', id: 'eng-b2-27', title: 'Unit 27: Technology Review', topic: 'Discussion and debate' },
            // Module 3: Arts & Culture (8 lessons)
            { module: 'Module 3: Arts & Culture', id: 'eng-b2-28', title: 'Unit 28: Literature', topic: 'Authors, Genres, Classics' },
            { module: 'Module 3: Arts & Culture', id: 'eng-b2-29', title: 'Unit 29: Cinema', topic: 'Directors, Reviews, Analysis' },
            { module: 'Module 3: Arts & Culture', id: 'eng-b2-30', title: 'Unit 30: Music', topic: 'Artists, Movements, Influence' },
            { module: 'Module 3: Arts & Culture', id: 'eng-b2-31', title: 'Unit 31: Art & Design', topic: 'Movements, Artists, Interpretation' },
            { module: 'Module 3: Arts & Culture', id: 'eng-b2-32', title: 'Unit 32: Inversion', topic: 'Not only..., Rarely..., Never...' },
            { module: 'Module 3: Arts & Culture', id: 'eng-b2-33', title: 'Unit 33: Cleft Sentences', topic: 'What I need is..., It was X who...' },
            { module: 'Module 3: Arts & Culture', id: 'eng-b2-34', title: 'Unit 34: Emphasis', topic: 'It is... that, The thing is...' },
            { module: 'Module 3: Arts & Culture', id: 'eng-b2-35', title: 'Unit 35: B2 Final Review', topic: 'Complete B2 review' },
            { module: 'Assessment', id: 'eng-b2-exam', type: 'exam', title: 'B2 Final Exam', topic: 'Upper Intermediate Assessment', requiredScore: 80 }
        ],
        'C1': [
            // Module 1: Global Issues (12 lessons)
            { module: 'Module 1: Global Issues', id: 'eng-c1-1', title: 'Unit 1: Globalization', topic: 'Trade, Economics, Impact' },
            { module: 'Module 1: Global Issues', id: 'eng-c1-2', title: 'Unit 2: Migration', topic: 'Immigration, Refugees, Integration' },
            { module: 'Module 1: Global Issues', id: 'eng-c1-3', title: 'Unit 3: Politics', topic: 'Government, Elections, Democracy' },
            { module: 'Module 1: Global Issues', id: 'eng-c1-4', title: 'Unit 4: International Relations', topic: 'Diplomacy, Conflicts, Treaties' },
            { module: 'Module 1: Global Issues', id: 'eng-c1-5', title: 'Unit 5: Economics', topic: 'Markets, Finance, Trade' },
            { module: 'Module 1: Global Issues', id: 'eng-c1-6', title: 'Unit 6: Ethics', topic: 'Moral dilemmas, Debates' },
            { module: 'Module 1: Global Issues', id: 'eng-c1-7', title: 'Unit 7: Advanced Connectors', topic: 'Notwithstanding, Hence, Thus' },
            { module: 'Module 1: Global Issues', id: 'eng-c1-8', title: 'Unit 8: Hedging Language', topic: 'Tend to, Appear to, Suggest' },
            { module: 'Module 1: Global Issues', id: 'eng-c1-9', title: 'Unit 9: Nominalisation', topic: 'Develop→Development, Analyse→Analysis' },
            { module: 'Module 1: Global Issues', id: 'eng-c1-10', title: 'Unit 10: Discourse Markers', topic: 'By contrast, In this respect' },
            { module: 'Module 1: Global Issues', id: 'eng-c1-11', title: 'Unit 11: Complex Sentences', topic: 'Multiple clauses, Embedding' },
            { module: 'Module 1: Global Issues', id: 'eng-c1-12', title: 'Unit 12: Issues Review', topic: 'Academic discussion' },
            // Module 2: Abstract Thought (12 lessons)
            { module: 'Module 2: Abstract Thought', id: 'eng-c1-13', title: 'Unit 13: Psychology', topic: 'Behavior, Mind, Motivation' },
            { module: 'Module 2: Abstract Thought', id: 'eng-c1-14', title: 'Unit 14: Philosophy', topic: 'Ethics, Logic, Existence' },
            { module: 'Module 2: Abstract Thought', id: 'eng-c1-15', title: 'Unit 15: Science', topic: 'Research, Methodology, Discovery' },
            { module: 'Module 2: Abstract Thought', id: 'eng-c1-16', title: 'Unit 16: Academic Writing', topic: 'Thesis, Arguments, Citations' },
            { module: 'Module 2: Abstract Thought', id: 'eng-c1-17', title: 'Unit 17: Research Papers', topic: 'Abstract, Introduction, Conclusion' },
            { module: 'Module 2: Abstract Thought', id: 'eng-c1-18', title: 'Unit 18: Advanced Inversion', topic: 'Not only...but, Hardly...when' },
            { module: 'Module 2: Abstract Thought', id: 'eng-c1-19', title: 'Unit 19: Cleft Sentences Advanced', topic: 'What matters is..., It was X who' },
            { module: 'Module 2: Abstract Thought', id: 'eng-c1-20', title: 'Unit 20: Subjunctive', topic: 'I suggest that he go, It is vital that' },
            { module: 'Module 2: Abstract Thought', id: 'eng-c1-21', title: 'Unit 21: Presentations', topic: 'Structure, Delivery, Visual aids' },
            { module: 'Module 2: Abstract Thought', id: 'eng-c1-22', title: 'Unit 22: Negotiations', topic: 'Proposals, Compromises, Agreements' },
            { module: 'Module 2: Abstract Thought', id: 'eng-c1-23', title: 'Unit 23: C1 Final Review', topic: 'Advanced structures practice' },
            { module: 'Assessment', id: 'eng-c1-exam', type: 'exam', title: 'C1 Final Exam', topic: 'Advanced Proficiency Assessment', requiredScore: 80 }
        ],
        'C2': [
            // Module 1: Mastery (15 lessons)
            { module: 'Module 1: Mastery', id: 'eng-c2-1', title: 'Unit 1: Rhetoric', topic: 'Persuasion, Argumentation, Logic' },
            { module: 'Module 1: Mastery', id: 'eng-c2-2', title: 'Unit 2: Public Speaking', topic: 'Speeches, Presentations, Debates' },
            { module: 'Module 1: Mastery', id: 'eng-c2-3', title: 'Unit 3: Literary Analysis', topic: 'Poetry, Prose, Criticism' },
            { module: 'Module 1: Mastery', id: 'eng-c2-4', title: 'Unit 4: Shakespeare', topic: 'Plays, Sonnets, Language' },
            { module: 'Module 1: Mastery', id: 'eng-c2-5', title: 'Unit 5: Modern Literature', topic: 'Contemporary authors and works' },
            { module: 'Module 1: Mastery', id: 'eng-c2-6', title: 'Unit 6: Nuance & Register', topic: 'Formal vs Informal, Tone' },
            { module: 'Module 1: Mastery', id: 'eng-c2-7', title: 'Unit 7: British English', topic: 'Vocabulary, Spelling, Expressions' },
            { module: 'Module 1: Mastery', id: 'eng-c2-8', title: 'Unit 8: American English', topic: 'Regional differences' },
            { module: 'Module 1: Mastery', id: 'eng-c2-9', title: 'Unit 9: Australian/Other', topic: 'World Englishes' },
            { module: 'Module 1: Mastery', id: 'eng-c2-10', title: 'Unit 10: Slang & Colloquial', topic: 'Informal expressions' },
            { module: 'Module 1: Mastery', id: 'eng-c2-11', title: 'Unit 11: Business English', topic: 'Negotiations, Contracts, Meetings' },
            { module: 'Module 1: Mastery', id: 'eng-c2-12', title: 'Unit 12: Legal English', topic: 'Contracts, Terms, Clauses' },
            { module: 'Module 1: Mastery', id: 'eng-c2-13', title: 'Unit 13: Medical English', topic: 'Terminology, Patient communication' },
            { module: 'Module 1: Mastery', id: 'eng-c2-14', title: 'Unit 14: Academic English', topic: 'Publishing, Peer review, Conferences' },
            { module: 'Module 1: Mastery', id: 'eng-c2-15', title: 'Unit 15: C2 Final Review', topic: 'Complete mastery review' },
            { module: 'Assessment', id: 'eng-c2-exam', type: 'exam', title: 'C2 Final Exam', topic: 'Mastery Assessment', requiredScore: 80 }
        ]
    }
};

// English total: 86 + 55 + 44 + 35 + 23 + 15 = 258 classes

module.exports = CURRICULUM;
