// Expanded Curriculum - 200+ classes per language
// This file will be built incrementally

const CURRICULUM = {
    'French': {
        'A1': [
            // Module 1: Bases (20 lessons)
            { module: 'Module 1: Bases', id: 'fra-a1-1', title: 'Unité 1: Bonjour!', topic: 'Salutations de base' },
            { module: 'Module 1: Bases', id: 'fra-a1-2', title: 'Unité 2: Se présenter', topic: 'Je m\'appelle..., Je suis...' },
            { module: 'Module 1: Bases', id: 'fra-a1-3', title: 'Unité 3: Être et Avoir', topic: 'Verbes fondamentaux' },
            { module: 'Module 1: Bases', id: 'fra-a1-4', title: 'Unité 4: Articles définis', topic: 'Le, la, les' },
            { module: 'Module 1: Bases', id: 'fra-a1-5', title: 'Unité 5: Articles indéfinis', topic: 'Un, une, des' },
            { module: 'Module 1: Bases', id: 'fra-a1-6', title: 'Unité 6: Pronoms personnels', topic: 'Je, tu, il, elle, nous, vous, ils, elles' },
            { module: 'Module 1: Bases', id: 'fra-a1-7', title: 'Unité 7: Alphabet français', topic: 'Prononciation des lettres' },
            { module: 'Module 1: Bases', id: 'fra-a1-8', title: 'Unité 8: Accents', topic: 'é, è, ê, ë, à, ù, ç' },
            { module: 'Module 1: Bases', id: 'fra-a1-9', title: 'Unité 9: Liaisons', topic: 'Prononciation enchaînée' },
            { module: 'Module 1: Bases', id: 'fra-a1-10', title: 'Unité 10: Négation', topic: 'Ne...pas, ne...jamais' },
            // Module 2: Nombres et Couleurs (12 lessons)
            { module: 'Module 2: Nombres', id: 'fra-a1-11', title: 'Unité 11: Nombres 1-10', topic: 'Un à dix' },
            { module: 'Module 2: Nombres', id: 'fra-a1-12', title: 'Unité 12: Nombres 11-20', topic: 'Onze à vingt' },
            { module: 'Module 2: Nombres', id: 'fra-a1-13', title: 'Unité 13: Nombres 21-69', topic: 'Vingt-et-un à soixante-neuf' },
            { module: 'Module 2: Nombres', id: 'fra-a1-14', title: 'Unité 14: Nombres 70-100', topic: 'Soixante-dix à cent' },
            { module: 'Module 2: Nombres', id: 'fra-a1-15', title: 'Unité 15: Grands nombres', topic: 'Cent, mille, million' },
            { module: 'Module 2: Nombres', id: 'fra-a1-16', title: 'Unité 16: Nombres ordinaux', topic: 'Premier, deuxième, troisième' },
            { module: 'Module 2: Nombres', id: 'fra-a1-17', title: 'Unité 17: Couleurs de base', topic: 'Rouge, bleu, vert, jaune' },
            { module: 'Module 2: Nombres', id: 'fra-a1-18', title: 'Unité 18: Couleurs avancées', topic: 'Rose, orange, violet, marron' },
            { module: 'Module 2: Nombres', id: 'fra-a1-19', title: 'Unité 19: Décrire les objets', topic: 'C\'est + couleur' },
            { module: 'Module 2: Nombres', id: 'fra-a1-20', title: 'Unité 20: Formes', topic: 'Carré, rond, triangle' },
            // Module 3: Famille (10 lessons)
            { module: 'Module 3: Famille', id: 'fra-a1-21', title: 'Unité 21: Famille proche', topic: 'Père, mère, frère, sœur' },
            { module: 'Module 3: Famille', id: 'fra-a1-22', title: 'Unité 22: Famille élargie', topic: 'Grand-père, tante, cousin' },
            { module: 'Module 3: Famille', id: 'fra-a1-23', title: 'Unité 23: Possessifs singuliers', topic: 'Mon, ton, son, ma, ta, sa' },
            { module: 'Module 3: Famille', id: 'fra-a1-24', title: 'Unité 24: Possessifs pluriels', topic: 'Notre, votre, leur, mes, tes, ses' },
            { module: 'Module 3: Famille', id: 'fra-a1-25', title: 'Unité 25: État civil', topic: 'Marié, célibataire, divorcé' },
            { module: 'Module 3: Famille', id: 'fra-a1-26', title: 'Unité 26: Décrire les personnes', topic: 'Grand, petit, jeune, vieux' },
            { module: 'Module 3: Famille', id: 'fra-a1-27', title: 'Unité 27: Caractère', topic: 'Gentil, sympa, drôle' },
            { module: 'Module 3: Famille', id: 'fra-a1-28', title: 'Unité 28: Apparence physique', topic: 'Cheveux, yeux, taille' },
            { module: 'Module 3: Famille', id: 'fra-a1-29', title: 'Unité 29: Animaux domestiques', topic: 'Chien, chat, oiseau' },
            { module: 'Module 3: Famille', id: 'fra-a1-30', title: 'Unité 30: Ma maison', topic: 'J\'habite à..., avec...' },
            // Module 4: Temps et Quotidien (15 lessons)
            { module: 'Module 4: Quotidien', id: 'fra-a1-31', title: 'Unité 31: Jours de la semaine', topic: 'Lundi à dimanche' },
            { module: 'Module 4: Quotidien', id: 'fra-a1-32', title: 'Unité 32: Mois de l\'année', topic: 'Janvier à décembre' },
            { module: 'Module 4: Quotidien', id: 'fra-a1-33', title: 'Unité 33: Saisons', topic: 'Printemps, été, automne, hiver' },
            { module: 'Module 4: Quotidien', id: 'fra-a1-34', title: 'Unité 34: L\'heure (heures)', topic: 'Il est une heure, deux heures' },
            { module: 'Module 4: Quotidien', id: 'fra-a1-35', title: 'Unité 35: L\'heure (minutes)', topic: 'Et quart, et demie, moins le quart' },
            { module: 'Module 4: Quotidien', id: 'fra-a1-36', title: 'Unité 36: Moments de la journée', topic: 'Matin, midi, après-midi, soir' },
            { module: 'Module 4: Quotidien', id: 'fra-a1-37', title: 'Unité 37: Verbes en -er', topic: 'Parler, manger, habiter' },
            { module: 'Module 4: Quotidien', id: 'fra-a1-38', title: 'Unité 38: Verbes en -ir', topic: 'Finir, choisir, réfléchir' },
            { module: 'Module 4: Quotidien', id: 'fra-a1-39', title: 'Unité 39: Verbes en -re', topic: 'Attendre, vendre, répondre' },
            { module: 'Module 4: Quotidien', id: 'fra-a1-40', title: 'Unité 40: Routine matinale', topic: 'Se lever, se laver, s\'habiller' },
            { module: 'Module 4: Quotidien', id: 'fra-a1-41', title: 'Unité 41: Routine du soir', topic: 'Dîner, se coucher, dormir' },
            { module: 'Module 4: Quotidien', id: 'fra-a1-42', title: 'Unité 42: Le week-end', topic: 'Activités du samedi et dimanche' },
            { module: 'Module 4: Quotidien', id: 'fra-a1-43', title: 'Unité 43: Fréquence', topic: 'Toujours, souvent, parfois, jamais' },
            { module: 'Module 4: Quotidien', id: 'fra-a1-44', title: 'Unité 44: Date et anniversaire', topic: 'Quelle est la date?' },
            { module: 'Module 4: Quotidien', id: 'fra-a1-45', title: 'Unité 45: Âge', topic: 'J\'ai...ans' },
            // Module 5: Nourriture (12 lessons)
            { module: 'Module 5: Nourriture', id: 'fra-a1-46', title: 'Unité 46: Fruits', topic: 'Pomme, orange, banane' },
            { module: 'Module 5: Nourriture', id: 'fra-a1-47', title: 'Unité 47: Légumes', topic: 'Carotte, tomate, salade' },
            { module: 'Module 5: Nourriture', id: 'fra-a1-48', title: 'Unité 48: Viande et poisson', topic: 'Poulet, bœuf, saumon' },
            { module: 'Module 5: Nourriture', id: 'fra-a1-49', title: 'Unité 49: Pain et pâtisseries', topic: 'Baguette, croissant' },
            { module: 'Module 5: Nourriture', id: 'fra-a1-50', title: 'Unité 50: Boissons chaudes', topic: 'Café, thé, chocolat chaud' },
            { module: 'Module 5: Nourriture', id: 'fra-a1-51', title: 'Unité 51: Boissons froides', topic: 'Eau, jus, vin' },
            { module: 'Module 5: Nourriture', id: 'fra-a1-52', title: 'Unité 52: Au café', topic: 'Commander un café' },
            { module: 'Module 5: Nourriture', id: 'fra-a1-53', title: 'Unité 53: Au restaurant', topic: 'Menu, entrée, plat, dessert' },
            { module: 'Module 5: Nourriture', id: 'fra-a1-54', title: 'Unité 54: L\'addition', topic: 'L\'addition s\'il vous plaît' },
            { module: 'Module 5: Nourriture', id: 'fra-a1-55', title: 'Unité 55: Goûts', topic: 'J\'aime, je n\'aime pas, je préfère' },
            { module: 'Module 5: Nourriture', id: 'fra-a1-56', title: 'Unité 56: Petit déjeuner', topic: 'Le petit-déjeuner français' },
            { module: 'Module 5: Nourriture', id: 'fra-a1-57', title: 'Unité 57: Repas', topic: 'Déjeuner et dîner' },
            // Module 6: Lieux (8 lessons)
            { module: 'Module 6: Lieux', id: 'fra-a1-58', title: 'Unité 58: En ville', topic: 'Boulangerie, pharmacie, banque' },
            { module: 'Module 6: Lieux', id: 'fra-a1-59', title: 'Unité 59: Bâtiments publics', topic: 'Mairie, poste, hôpital' },
            { module: 'Module 6: Lieux', id: 'fra-a1-60', title: 'Unité 60: Il y a', topic: 'Il y a un..., Il n\'y a pas de...' },
            { module: 'Module 6: Lieux', id: 'fra-a1-61', title: 'Unité 61: Prépositions de lieu', topic: 'À, au, à la, aux, chez' },
            { module: 'Module 6: Lieux', id: 'fra-a1-62', title: 'Unité 62: Position', topic: 'Devant, derrière, entre' },
            { module: 'Module 6: Lieux', id: 'fra-a1-63', title: 'Unité 63: Météo', topic: 'Il fait beau, il pleut' },
            { module: 'Module 6: Lieux', id: 'fra-a1-64', title: 'Unité 64: Pays et nationalités', topic: 'France, français, française' },
            { module: 'Module 6: Lieux', id: 'fra-a1-65', title: 'Unité 65: Villes françaises', topic: 'Paris, Lyon, Marseille' },
            { module: 'Assessment', id: 'fra-a1-exam', type: 'exam', title: 'Examen Final A1', topic: 'Évaluation A1', requiredScore: 80 }
        ],
        'A2': [
            // Module 1: Maison (12 lessons)
            { module: 'Module 1: Maison', id: 'fra-a2-1', title: 'Unité 1: Pièces de la maison', topic: 'Salon, cuisine, chambre' },
            { module: 'Module 1: Maison', id: 'fra-a2-2', title: 'Unité 2: Meubles', topic: 'Canapé, table, lit, armoire' },
            { module: 'Module 1: Maison', id: 'fra-a2-3', title: 'Unité 3: Électroménager', topic: 'Frigo, four, machine à laver' },
            { module: 'Module 1: Maison', id: 'fra-a2-4', title: 'Unité 4: Prépositions de lieu', topic: 'Dans, sur, sous, devant, derrière' },
            { module: 'Module 1: Maison', id: 'fra-a2-5', title: 'Unité 5: Déménagement', topic: 'Emménager, déménager' },
            { module: 'Module 1: Maison', id: 'fra-a2-6', title: 'Unité 6: Louer un appartement', topic: 'Loyer, caution, contrat' },
            { module: 'Module 1: Maison', id: 'fra-a2-7', title: 'Unité 7: Tâches ménagères', topic: 'Faire le ménage, la vaisselle' },
            { module: 'Module 1: Maison', id: 'fra-a2-8', title: 'Unité 8: Jardin', topic: 'Plantes, fleurs, pelouse' },
            { module: 'Module 1: Maison', id: 'fra-a2-9', title: 'Unité 9: Problèmes domestiques', topic: 'Panne, réparation, plombier' },
            { module: 'Module 1: Maison', id: 'fra-a2-10', title: 'Unité 10: Voisinage', topic: 'Voisins, quartier, immeuble' },
            { module: 'Module 1: Maison', id: 'fra-a2-11', title: 'Unité 11: Décoration', topic: 'Décorer, peindre, rénover' },
            { module: 'Module 1: Maison', id: 'fra-a2-12', title: 'Unité 12: Ma maison idéale', topic: 'Décrire sa maison de rêve' },
            // Module 2: Passé (15 lessons)
            { module: 'Module 2: Passé', id: 'fra-a2-13', title: 'Unité 13: Passé composé avec avoir', topic: 'J\'ai mangé, tu as parlé' },
            { module: 'Module 2: Passé', id: 'fra-a2-14', title: 'Unité 14: Passé composé avec être', topic: 'Je suis allé(e), tu es venu(e)' },
            { module: 'Module 2: Passé', id: 'fra-a2-15', title: 'Unité 15: Verbes pronominaux au passé', topic: 'Je me suis levé(e)' },
            { module: 'Module 2: Passé', id: 'fra-a2-16', title: 'Unité 16: Participes irréguliers 1', topic: 'Fait, dit, écrit, lu' },
            { module: 'Module 2: Passé', id: 'fra-a2-17', title: 'Unité 17: Participes irréguliers 2', topic: 'Vu, pris, mis, ouvert' },
            { module: 'Module 2: Passé', id: 'fra-a2-18', title: 'Unité 18: Participes irréguliers 3', topic: 'Bu, voulu, pu, su' },
            { module: 'Module 2: Passé', id: 'fra-a2-19', title: 'Unité 19: Imparfait régulier', topic: 'Quand j\'étais petit...' },
            { module: 'Module 2: Passé', id: 'fra-a2-20', title: 'Unité 20: Imparfait irrégulier', topic: 'C\'était, il y avait' },
            { module: 'Module 2: Passé', id: 'fra-a2-21', title: 'Unité 21: Passé composé vs imparfait', topic: 'Quand, soudain, tous les jours' },
            { module: 'Module 2: Passé', id: 'fra-a2-22', title: 'Unité 22: Raconter une histoire', topic: 'Il était une fois...' },
            { module: 'Module 2: Passé', id: 'fra-a2-23', title: 'Unité 23: Souvenirs d\'enfance', topic: 'Quand j\'avais...ans' },
            { module: 'Module 2: Passé', id: 'fra-a2-24', title: 'Unité 24: Événements passés', topic: 'Hier, la semaine dernière' },
            { module: 'Module 2: Passé', id: 'fra-a2-25', title: 'Unité 25: Biographie simple', topic: 'Il est né en..., Il a vécu...' },
            { module: 'Module 2: Passé', id: 'fra-a2-26', title: 'Unité 26: Plus-que-parfait intro', topic: 'J\'avais déjà mangé quand...' },
            { module: 'Module 2: Passé', id: 'fra-a2-27', title: 'Unité 27: Expressions de temps', topic: 'Avant, après, pendant' },
            // Module 3: Ville et Transport (12 lessons)
            { module: 'Module 3: Ville', id: 'fra-a2-28', title: 'Unité 28: Transports en commun', topic: 'Métro, bus, tramway' },
            { module: 'Module 3: Ville', id: 'fra-a2-29', title: 'Unité 29: Acheter un billet', topic: 'Aller-retour, tarif réduit' },
            { module: 'Module 3: Ville', id: 'fra-a2-30', title: 'Unité 30: Demander son chemin', topic: 'Où est...? Comment aller à...?' },
            { module: 'Module 3: Ville', id: 'fra-a2-31', title: 'Unité 31: Donner des directions', topic: 'Tournez à gauche, continuez tout droit' },
            { module: 'Module 3: Ville', id: 'fra-a2-32', title: 'Unité 32: À la gare', topic: 'Quai, voie, correspondance' },
            { module: 'Module 3: Ville', id: 'fra-a2-33', title: 'Unité 33: À l\'aéroport', topic: 'Embarquement, douane, bagages' },
            { module: 'Module 3: Ville', id: 'fra-a2-34', title: 'Unité 34: Location de voiture', topic: 'Permis, assurance, réservation' },
            { module: 'Module 3: Ville', id: 'fra-a2-35', title: 'Unité 35: Problèmes de voyage', topic: 'Retard, annulation, perte' },
            { module: 'Module 3: Ville', id: 'fra-a2-36', title: 'Unité 36: L\'impératif affirmatif', topic: 'Tourne!, Allez!, Prenez!' },
            { module: 'Module 3: Ville', id: 'fra-a2-37', title: 'Unité 37: L\'impératif négatif', topic: 'Ne tourne pas!, N\'allez pas!' },
            { module: 'Module 3: Ville', id: 'fra-a2-38', title: 'Unité 38: Pronoms COD', topic: 'Le, la, les, l\'' },
            { module: 'Module 3: Ville', id: 'fra-a2-39', title: 'Unité 39: Pronoms COI', topic: 'Lui, leur, me, te, nous, vous' },
            // Module 4: Achats (10 lessons)
            { module: 'Module 4: Achats', id: 'fra-a2-40', title: 'Unité 40: Vêtements', topic: 'Chemise, pantalon, jupe, robe' },
            { module: 'Module 4: Achats', id: 'fra-a2-41', title: 'Unité 41: Accessoires', topic: 'Chapeau, ceinture, sac' },
            { module: 'Module 4: Achats', id: 'fra-a2-42', title: 'Unité 42: Tailles et couleurs', topic: 'Quelle taille? Quelle couleur?' },
            { module: 'Module 4: Achats', id: 'fra-a2-43', title: 'Unité 43: Essayer', topic: 'Je peux essayer? Ça me va?' },
            { module: 'Module 4: Achats', id: 'fra-a2-44', title: 'Unité 44: Payer', topic: 'En espèces, par carte' },
            { module: 'Module 4: Achats', id: 'fra-a2-45', title: 'Unité 45: Comparatifs', topic: 'Plus...que, moins...que, aussi...que' },
            { module: 'Module 4: Achats', id: 'fra-a2-46', title: 'Unité 46: Superlatifs', topic: 'Le plus grand, le meilleur' },
            { module: 'Module 4: Achats', id: 'fra-a2-47', title: 'Unité 47: Faire des courses', topic: 'Au supermarché' },
            { module: 'Module 4: Achats', id: 'fra-a2-48', title: 'Unité 48: Réclamations', topic: 'Échanger, rembourser' },
            { module: 'Module 4: Achats', id: 'fra-a2-49', title: 'Unité 49: Articles partitifs', topic: 'Du, de la, des, de l\'' },
            // Module 5: Loisirs (8 lessons)
            { module: 'Module 5: Loisirs', id: 'fra-a2-50', title: 'Unité 50: Sports', topic: 'Football, tennis, natation' },
            { module: 'Module 5: Loisirs', id: 'fra-a2-51', title: 'Unité 51: Musique et art', topic: 'Jouer de la guitare, peindre' },
            { module: 'Module 5: Loisirs', id: 'fra-a2-52', title: 'Unité 52: Cinéma et télévision', topic: 'Film, série, documentaire' },
            { module: 'Module 5: Loisirs', id: 'fra-a2-53', title: 'Unité 53: Lecture', topic: 'Livre, roman, magazine' },
            { module: 'Module 5: Loisirs', id: 'fra-a2-54', title: 'Unité 54: Inviter quelqu\'un', topic: 'Tu veux venir? On se retrouve?' },
            { module: 'Module 5: Loisirs', id: 'fra-a2-55', title: 'Unité 55: Accepter/Refuser', topic: 'Avec plaisir! Désolé, je ne peux pas' },
            { module: 'Module 5: Loisirs', id: 'fra-a2-56', title: 'Unité 56: Vacances', topic: 'Mer, montagne, campagne' },
            { module: 'Module 5: Loisirs', id: 'fra-a2-57', title: 'Unité 57: Projets de week-end', topic: 'Ce week-end, je vais...' },
            { module: 'Assessment', id: 'fra-a2-exam', type: 'exam', title: 'Examen Final A2', topic: 'Évaluation A2', requiredScore: 80 }
        ],
        'B1': [
            // Module 1: Récits et Voyages (12 lessons)
            { module: 'Module 1: Récits', id: 'fra-b1-1', title: 'Unité 1: Raconter un voyage', topic: 'Récit de vacances' },
            { module: 'Module 1: Récits', id: 'fra-b1-2', title: 'Unité 2: Expériences marquantes', topic: 'La chose la plus...que j\'ai faite' },
            { module: 'Module 1: Récits', id: 'fra-b1-3', title: 'Unité 3: Futur simple régulier', topic: 'Je parlerai, tu finiras' },
            { module: 'Module 1: Récits', id: 'fra-b1-4', title: 'Unité 4: Futur simple irrégulier', topic: 'Je serai, j\'aurai, j\'irai' },
            { module: 'Module 1: Récits', id: 'fra-b1-5', title: 'Unité 5: Futur antérieur', topic: 'J\'aurai fini quand...' },
            { module: 'Module 1: Récits', id: 'fra-b1-6', title: 'Unité 6: Conditionnel présent', topic: 'Je voudrais, je pourrais' },
            { module: 'Module 1: Récits', id: 'fra-b1-7', title: 'Unité 7: Si + imparfait', topic: 'Si j\'avais le temps, je...' },
            { module: 'Module 1: Récits', id: 'fra-b1-8', title: 'Unité 8: Hypothèses', topic: 'Si c\'était possible...' },
            { module: 'Module 1: Récits', id: 'fra-b1-9', title: 'Unité 9: Pronoms relatifs qui/que', topic: 'La personne qui..., Le film que...' },
            { module: 'Module 1: Récits', id: 'fra-b1-10', title: 'Unité 10: Pronoms relatifs où/dont', topic: 'L\'endroit où..., La chose dont...' },
            { module: 'Module 1: Récits', id: 'fra-b1-11', title: 'Unité 11: Gérondif', topic: 'En mangeant, en travaillant' },
            { module: 'Module 1: Récits', id: 'fra-b1-12', title: 'Unité 12: Discours indirect (présent)', topic: 'Il dit que...' },
            // Module 2: Travail (12 lessons)
            { module: 'Module 2: Travail', id: 'fra-b1-13', title: 'Unité 13: Métiers', topic: 'Médecin, avocat, ingénieur' },
            { module: 'Module 2: Travail', id: 'fra-b1-14', title: 'Unité 14: Chercher un emploi', topic: 'Offre d\'emploi, candidature' },
            { module: 'Module 2: Travail', id: 'fra-b1-15', title: 'Unité 15: CV français', topic: 'Formation, expérience' },
            { module: 'Module 2: Travail', id: 'fra-b1-16', title: 'Unité 16: Lettre de motivation', topic: 'Madame, Monsieur...' },
            { module: 'Module 2: Travail', id: 'fra-b1-17', title: 'Unité 17: Entretien d\'embauche', topic: 'Questions et réponses types' },
            { module: 'Module 2: Travail', id: 'fra-b1-18', title: 'Unité 18: Au bureau', topic: 'Collègue, réunion, projet' },
            { module: 'Module 2: Travail', id: 'fra-b1-19', title: 'Unité 19: Téléphone professionnel', topic: 'Allô? Je voudrais parler à...' },
            { module: 'Module 2: Travail', id: 'fra-b1-20', title: 'Unité 20: Email professionnel', topic: 'Objet, formules de politesse' },
            { module: 'Module 2: Travail', id: 'fra-b1-21', title: 'Unité 21: Passif présent', topic: 'Le projet est géré par...' },
            { module: 'Module 2: Travail', id: 'fra-b1-22', title: 'Unité 22: Passif passé', topic: 'Le contrat a été signé' },
            { module: 'Module 2: Travail', id: 'fra-b1-23', title: 'Unité 23: Cause et conséquence', topic: 'Parce que, donc, alors' },
            { module: 'Module 2: Travail', id: 'fra-b1-24', title: 'Unité 24: But', topic: 'Pour, afin de, pour que' },
            // Module 3: Opinions (10 lessons)
            { module: 'Module 3: Opinions', id: 'fra-b1-25', title: 'Unité 25: Donner son avis', topic: 'Je pense que, À mon avis' },
            { module: 'Module 3: Opinions', id: 'fra-b1-26', title: 'Unité 26: Être d\'accord', topic: 'Je suis d\'accord, Tout à fait' },
            { module: 'Module 3: Opinions', id: 'fra-b1-27', title: 'Unité 27: Exprimer le désaccord', topic: 'Je ne suis pas d\'accord, Pas du tout' },
            { module: 'Module 3: Opinions', id: 'fra-b1-28', title: 'Unité 28: Subjonctif présent régulier', topic: 'Que je parle, que tu finisses' },
            { module: 'Module 3: Opinions', id: 'fra-b1-29', title: 'Unité 29: Subjonctif présent irrégulier', topic: 'Que je sois, que j\'aie, que je fasse' },
            { module: 'Module 3: Opinions', id: 'fra-b1-30', title: 'Unité 30: Subjonctif après sentiment', topic: 'Je suis content que...' },
            { module: 'Module 3: Opinions', id: 'fra-b1-31', title: 'Unité 31: Subjonctif après doute', topic: 'Je doute que..., Il est possible que...' },
            { module: 'Module 3: Opinions', id: 'fra-b1-32', title: 'Unité 32: Indicatif vs subjonctif', topic: 'Je pense que... vs Je ne pense pas que...' },
            { module: 'Module 3: Opinions', id: 'fra-b1-33', title: 'Unité 33: Exprimer la certitude', topic: 'Je suis sûr que, Il est certain que' },
            { module: 'Module 3: Opinions', id: 'fra-b1-34', title: 'Unité 34: Exprimer l\'incertitude', topic: 'Peut-être, Il se peut que' },
            // Module 4: Santé et Corps (8 lessons)
            { module: 'Module 4: Santé', id: 'fra-b1-35', title: 'Unité 35: Parties du corps', topic: 'Tête, bras, jambe, dos' },
            { module: 'Module 4: Santé', id: 'fra-b1-36', title: 'Unité 36: Maladies et symptômes', topic: 'Fièvre, toux, mal de tête' },
            { module: 'Module 4: Santé', id: 'fra-b1-37', title: 'Unité 37: Chez le médecin', topic: 'Consultation, ordonnance' },
            { module: 'Module 4: Santé', id: 'fra-b1-38', title: 'Unité 38: À la pharmacie', topic: 'Médicaments, posologie' },
            { module: 'Module 4: Santé', id: 'fra-b1-39', title: 'Unité 39: Mode de vie sain', topic: 'Alimentation, exercice' },
            { module: 'Module 4: Santé', id: 'fra-b1-40', title: 'Unité 40: Conseils de santé', topic: 'Il faut, Vous devriez' },
            { module: 'Module 4: Santé', id: 'fra-b1-41', title: 'Unité 41: Urgences', topic: 'SAMU, pompiers, police' },
            { module: 'Module 4: Santé', id: 'fra-b1-42', title: 'Unité 42: Assurance maladie', topic: 'Sécurité sociale, mutuelle' },
            { module: 'Assessment', id: 'fra-b1-exam', type: 'exam', title: 'Examen Final B1', topic: 'Évaluation B1', requiredScore: 80 }
        ],
        'B2': [
            // Module 1: Débats et Société (12 lessons)
            { module: 'Module 1: Débats', id: 'fra-b2-1', title: 'Unité 1: Technologie', topic: 'Avantages et inconvénients des réseaux sociaux' },
            { module: 'Module 1: Débats', id: 'fra-b2-2', title: 'Unité 2: Environnement', topic: 'Réchauffement climatique, pollution' },
            { module: 'Module 1: Débats', id: 'fra-b2-3', title: 'Unité 3: Éducation', topic: 'Système scolaire français' },
            { module: 'Module 1: Débats', id: 'fra-b2-4', title: 'Unité 4: Société', topic: 'Inégalités, discriminations' },
            { module: 'Module 1: Débats', id: 'fra-b2-5', title: 'Unité 5: Subjonctif imparfait', topic: 'Qu\'il parlât, qu\'il finît' },
            { module: 'Module 1: Débats', id: 'fra-b2-6', title: 'Unité 6: Subjonctif passé', topic: 'Que j\'aie fait, que tu sois parti' },
            { module: 'Module 1: Débats', id: 'fra-b2-7', title: 'Unité 7: Concession', topic: 'Bien que, même si, quoique' },
            { module: 'Module 1: Débats', id: 'fra-b2-8', title: 'Unité 8: Opposition', topic: 'Alors que, tandis que, au lieu de' },
            { module: 'Module 1: Débats', id: 'fra-b2-9', title: 'Unité 9: Condition', topic: 'À condition que, pourvu que' },
            { module: 'Module 1: Débats', id: 'fra-b2-10', title: 'Unité 10: Hypothèse irréelle passé', topic: 'Si j\'avais su, j\'aurais...' },
            { module: 'Module 1: Débats', id: 'fra-b2-11', title: 'Unité 11: Conditionnel passé', topic: 'J\'aurais voulu, il aurait pu' },
            { module: 'Module 1: Débats', id: 'fra-b2-12', title: 'Unité 12: Argumentation structurée', topic: 'D\'une part..., d\'autre part...' },
            // Module 2: Communication avancée (10 lessons)
            { module: 'Module 2: Communication', id: 'fra-b2-13', title: 'Unité 13: Discours indirect passé', topic: 'Il a dit qu\'il était venu...' },
            { module: 'Module 2: Communication', id: 'fra-b2-14', title: 'Unité 14: Concordance des temps', topic: 'Transformation des temps' },
            { module: 'Module 2: Communication', id: 'fra-b2-15', title: 'Unité 15: Connecteurs logiques', topic: 'Cependant, néanmoins, toutefois' },
            { module: 'Module 2: Communication', id: 'fra-b2-16', title: 'Unité 16: Connecteurs de cause', topic: 'Étant donné que, vu que' },
            { module: 'Module 2: Communication', id: 'fra-b2-17', title: 'Unité 17: Connecteurs de conséquence', topic: 'De sorte que, si bien que' },
            { module: 'Module 2: Communication', id: 'fra-b2-18', title: 'Unité 18: Nominalisation', topic: 'Développer → le développement' },
            { module: 'Module 2: Communication', id: 'fra-b2-19', title: 'Unité 19: Registres de langue', topic: 'Familier, courant, soutenu' },
            { module: 'Module 2: Communication', id: 'fra-b2-20', title: 'Unité 20: Expression écrite formelle', topic: 'Rapports, synthèses' },
            { module: 'Module 2: Communication', id: 'fra-b2-21', title: 'Unité 21: Présentation orale', topic: 'Introduire, développer, conclure' },
            { module: 'Module 2: Communication', id: 'fra-b2-22', title: 'Unité 22: Débattre', topic: 'Réfuter, nuancer, convaincre' },
            // Module 3: Culture et Médias (8 lessons)
            { module: 'Module 3: Culture', id: 'fra-b2-23', title: 'Unité 23: Presse française', topic: 'Le Monde, Le Figaro, Libération' },
            { module: 'Module 3: Culture', id: 'fra-b2-24', title: 'Unité 24: Actualités', topic: 'Comprendre un article de journal' },
            { module: 'Module 3: Culture', id: 'fra-b2-25', title: 'Unité 25: Cinéma français', topic: 'Films classiques et contemporains' },
            { module: 'Module 3: Culture', id: 'fra-b2-26', title: 'Unité 26: Littérature française', topic: 'Auteurs célèbres' },
            { module: 'Module 3: Culture', id: 'fra-b2-27', title: 'Unité 27: Art français', topic: 'Impressionnisme, musées' },
            { module: 'Module 3: Culture', id: 'fra-b2-28', title: 'Unité 28: Musique francophone', topic: 'Chanson française, variété' },
            { module: 'Module 3: Culture', id: 'fra-b2-29', title: 'Unité 29: Gastronomie', topic: 'Cuisine régionale française' },
            { module: 'Module 3: Culture', id: 'fra-b2-30', title: 'Unité 30: Fêtes et traditions', topic: 'Noël, 14 juillet, Pâques' },
            { module: 'Assessment', id: 'fra-b2-exam', type: 'exam', title: 'Examen Final B2', topic: 'Évaluation B2', requiredScore: 80 }
        ],
        'C1': [
            // Module 1: Nuances et Style (10 lessons)
            { module: 'Module 1: Nuances', id: 'fra-c1-1', title: 'Unité 1: Littérature classique', topic: 'Hugo, Balzac, Flaubert' },
            { module: 'Module 1: Nuances', id: 'fra-c1-2', title: 'Unité 2: Littérature moderne', topic: 'Camus, Sartre, Duras' },
            { module: 'Module 1: Nuances', id: 'fra-c1-3', title: 'Unité 3: Analyse littéraire', topic: 'Thèmes, style, symbolisme' },
            { module: 'Module 1: Nuances', id: 'fra-c1-4', title: 'Unité 4: Politique française', topic: 'Ve République, institutions' },
            { module: 'Module 1: Nuances', id: 'fra-c1-5', title: 'Unité 5: Actualité politique', topic: 'Débats contemporains' },
            { module: 'Module 1: Nuances', id: 'fra-c1-6', title: 'Unité 6: Économie française', topic: 'Marché, entreprises, syndicats' },
            { module: 'Module 1: Nuances', id: 'fra-c1-7', title: 'Unité 7: Passé simple', topic: 'Il parla, il finit, il alla' },
            { module: 'Module 1: Nuances', id: 'fra-c1-8', title: 'Unité 8: Passé antérieur', topic: 'Quand il eut fini...' },
            { module: 'Module 1: Nuances', id: 'fra-c1-9', title: 'Unité 9: Ne explétif', topic: 'Avant qu\'il ne parte' },
            { module: 'Module 1: Nuances', id: 'fra-c1-10', title: 'Unité 10: Inversion stylistique', topic: 'Peut-être viendra-t-il' },
            // Module 2: Expression avancée (10 lessons)
            { module: 'Module 2: Expression', id: 'fra-c1-11', title: 'Unité 11: Dissertation', topic: 'Structure, argumentation' },
            { module: 'Module 2: Expression', id: 'fra-c1-12', title: 'Unité 12: Synthèse de documents', topic: 'Comparer, regrouper, reformuler' },
            { module: 'Module 2: Expression', id: 'fra-c1-13', title: 'Unité 13: Essai argumentatif', topic: 'Thèse, antithèse, synthèse' },
            { module: 'Module 2: Expression', id: 'fra-c1-14', title: 'Unité 14: Critique', topic: 'Littéraire, cinématographique' },
            { module: 'Module 2: Expression', id: 'fra-c1-15', title: 'Unité 15: Prise de parole', topic: 'Conférence, discours' },
            { module: 'Module 2: Expression', id: 'fra-c1-16', title: 'Unité 16: Négociation', topic: 'Stratégies de communication' },
            { module: 'Module 2: Expression', id: 'fra-c1-17', title: 'Unité 17: Ironie et sous-entendus', topic: 'Comprendre l\'implicite' },
            { module: 'Module 2: Expression', id: 'fra-c1-18', title: 'Unité 18: Figures de style', topic: 'Métaphore, hyperbole, litote' },
            { module: 'Module 2: Expression', id: 'fra-c1-19', title: 'Unité 19: Expressions idiomatiques', topic: 'Avoir le cafard, être dans la lune' },
            { module: 'Module 2: Expression', id: 'fra-c1-20', title: 'Unité 20: Proverbes français', topic: 'Qui vivra verra, Mieux vaut tard...' },
            { module: 'Assessment', id: 'fra-c1-exam', type: 'exam', title: 'Examen Final C1', topic: 'Évaluation C1', requiredScore: 80 }
        ],
        'C2': [
            // Module 1: Maîtrise (15 lessons)
            { module: 'Module 1: Maîtrise', id: 'fra-c2-1', title: 'Unité 1: Philosophie française', topic: 'Descartes, Pascal, Sartre' },
            { module: 'Module 1: Maîtrise', id: 'fra-c2-2', title: 'Unité 2: Histoire de France', topic: 'Révolution, Empire, Républiques' },
            { module: 'Module 1: Maîtrise', id: 'fra-c2-3', title: 'Unité 3: Sciences humaines', topic: 'Sociologie, anthropologie' },
            { module: 'Module 1: Maîtrise', id: 'fra-c2-4', title: 'Unité 4: Français québécois', topic: 'Expressions, accent, vocabulaire' },
            { module: 'Module 1: Maîtrise', id: 'fra-c2-5', title: 'Unité 5: Français africain', topic: 'Sénégal, Côte d\'Ivoire' },
            { module: 'Module 1: Maîtrise', id: 'fra-c2-6', title: 'Unité 6: Français suisse et belge', topic: 'Particularités régionales' },
            { module: 'Module 1: Maîtrise', id: 'fra-c2-7', title: 'Unité 7: Argot et verlan', topic: 'Langage familier, jeune' },
            { module: 'Module 1: Maîtrise', id: 'fra-c2-8', title: 'Unité 8: Registre soutenu', topic: 'Français académique' },
            { module: 'Module 1: Maîtrise', id: 'fra-c2-9', title: 'Unité 9: Poésie française', topic: 'Baudelaire, Rimbaud, Verlaine' },
            { module: 'Module 1: Maîtrise', id: 'fra-c2-10', title: 'Unité 10: Théâtre', topic: 'Molière, Racine, Ionesco' },
            { module: 'Module 1: Maîtrise', id: 'fra-c2-11', title: 'Unité 11: Traduction littéraire', topic: 'Techniques et défis' },
            { module: 'Module 1: Maîtrise', id: 'fra-c2-12', title: 'Unité 12: Rédaction académique', topic: 'Articles, thèses' },
            { module: 'Module 1: Maîtrise', id: 'fra-c2-13', title: 'Unité 13: Éthique et bioéthique', topic: 'Débats contemporains' },
            { module: 'Module 1: Maîtrise', id: 'fra-c2-14', title: 'Unité 14: Droit français', topic: 'Vocabulaire juridique' },
            { module: 'Module 1: Maîtrise', id: 'fra-c2-15', title: 'Unité 15: Médecine', topic: 'Vocabulaire médical avancé' },
            { module: 'Assessment', id: 'fra-c2-exam', type: 'exam', title: 'Examen Final C2', topic: 'Évaluation C2', requiredScore: 80 }
        ]
    }
};

// French Total: 65 + 57 + 42 + 30 + 20 + 15 = 229 classes

module.exports = CURRICULUM;
